import { Theme, Template } from './types';

// Default Theme
export const defaultTheme: Theme = {
  id: 'default',
  name: 'Default',
  colors: {
    primary: '#3b82f6',
    secondary: '#6366f1',
    accent: '#f59e0b',
    background: '#ffffff',
    text: '#1f2937',
    textSecondary: '#6b7280',
  },
  typography: {
    headingFont: 'Inter',
    bodyFont: 'Inter',
    baseSize: 16,
  },
  borderRadius: 8,
  spacing: 24,
};

// Available Themes
export const themes: Theme[] = [
  defaultTheme,
  // Rose Theme - Adobe Portfolio inspired
  {
    id: 'rose',
    name: 'Rose',
    colors: {
      primary: '#ba9f99',
      secondary: '#9e796a',
      accent: '#ea9a80',
      background: '#f7f4f3',
      text: '#111111',
      textSecondary: '#6e6e6e',
    },
    typography: {
      headingFont: 'Playfair Display',
      bodyFont: 'Lato',
      baseSize: 16,
    },
    borderRadius: 4,
    spacing: 32,
  },
  // Dark Themes
  {
    id: 'midnight',
    name: 'Midnight',
    colors: {
      primary: '#60a5fa',
      secondary: '#818cf8',
      accent: '#fbbf24',
      background: '#111827',
      text: '#f9fafb',
      textSecondary: '#9ca3af',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      baseSize: 16,
    },
    borderRadius: 8,
    spacing: 24,
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    colors: {
      primary: '#00d4ff',
      secondary: '#7c3aed',
      accent: '#10b981',
      background: '#0f172a',
      text: '#f1f5f9',
      textSecondary: '#94a3b8',
    },
    typography: {
      headingFont: 'Space Grotesk',
      bodyFont: 'Inter',
      baseSize: 16,
    },
    borderRadius: 12,
    spacing: 24,
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    colors: {
      primary: '#1769ff',
      secondary: '#245bff',
      accent: '#ff6b6b',
      background: '#191919',
      text: '#ffffff',
      textSecondary: '#959595',
    },
    typography: {
      headingFont: 'Poppins',
      bodyFont: 'Inter',
      baseSize: 16,
    },
    borderRadius: 4,
    spacing: 24,
  },
  // Light Minimal Themes
  {
    id: 'minimalist',
    name: 'Minimalist',
    colors: {
      primary: '#18181b',
      secondary: '#3f3f46',
      accent: '#18181b',
      background: '#fafafa',
      text: '#18181b',
      textSecondary: '#71717a',
    },
    typography: {
      headingFont: 'Inter',
      bodyFont: 'Inter',
      baseSize: 16,
    },
    borderRadius: 0,
    spacing: 20,
  },
  {
    id: 'editorial',
    name: 'Editorial',
    colors: {
      primary: '#000000',
      secondary: '#333333',
      accent: '#ff0000',
      background: '#ffffff',
      text: '#000000',
      textSecondary: '#666666',
    },
    typography: {
      headingFont: 'Playfair Display',
      bodyFont: 'Georgia',
      baseSize: 17,
    },
    borderRadius: 0,
    spacing: 36,
  },
  // Creative & Artistic Themes
  {
    id: 'neon-pop',
    name: 'Neon Pop',
    colors: {
      primary: '#ec4899',
      secondary: '#8b5cf6',
      accent: '#06b6d4',
      background: '#fafafa',
      text: '#1f2937',
      textSecondary: '#6b7280',
    },
    typography: {
      headingFont: 'Playfair Display',
      bodyFont: 'Lato',
      baseSize: 16,
    },
    borderRadius: 16,
    spacing: 32,
  },
  {
    id: 'aurora',
    name: 'Aurora',
    colors: {
      primary: '#667eea',
      secondary: '#764ba2',
      accent: '#f093fb',
      background: '#ffffff',
      text: '#1a1a2e',
      textSecondary: '#6b7280',
    },
    typography: {
      headingFont: 'Poppins',
      bodyFont: 'Inter',
      baseSize: 16,
    },
    borderRadius: 12,
    spacing: 24,
  },
  // Professional & Corporate Themes
  {
    id: 'corporate',
    name: 'Corporate',
    colors: {
      primary: '#1e40af',
      secondary: '#1e3a8a',
      accent: '#b45309',
      background: '#ffffff',
      text: '#1f2937',
      textSecondary: '#4b5563',
    },
    typography: {
      headingFont: 'Playfair Display',
      bodyFont: 'Lora',
      baseSize: 16,
    },
    borderRadius: 4,
    spacing: 24,
  },
  {
    id: 'slate',
    name: 'Slate',
    colors: {
      primary: '#2d3436',
      secondary: '#636e72',
      accent: '#0984e3',
      background: '#ffffff',
      text: '#2d3436',
      textSecondary: '#636e72',
    },
    typography: {
      headingFont: 'Montserrat',
      bodyFont: 'Roboto',
      baseSize: 16,
    },
    borderRadius: 0,
    spacing: 32,
  },
  // Platform-Inspired Themes
  {
    id: 'behance',
    name: 'Behance',
    colors: {
      primary: '#1769ff',
      secondary: '#0057ff',
      accent: '#ff4d4d',
      background: '#ffffff',
      text: '#191919',
      textSecondary: '#6e6e6e',
    },
    typography: {
      headingFont: 'Poppins',
      bodyFont: 'Inter',
      baseSize: 16,
    },
    borderRadius: 4,
    spacing: 24,
  },
  {
    id: 'dribbble',
    name: 'Dribbble',
    colors: {
      primary: '#ea4c89',
      secondary: '#c32361',
      accent: '#f06292',
      background: '#ffffff',
      text: '#333333',
      textSecondary: '#6d6d6d',
    },
    typography: {
      headingFont: 'Montserrat',
      bodyFont: 'Inter',
      baseSize: 16,
    },
    borderRadius: 8,
    spacing: 24,
  },
  // Nature & Earth Themes
  {
    id: 'forest',
    name: 'Forest',
    colors: {
      primary: '#059669',
      secondary: '#0d9488',
      accent: '#84cc16',
      background: '#f0fdf4',
      text: '#14532d',
      textSecondary: '#166534',
    },
    typography: {
      headingFont: 'Merriweather',
      bodyFont: 'Open Sans',
      baseSize: 16,
    },
    borderRadius: 12,
    spacing: 28,
  },
  {
    id: 'terracotta',
    name: 'Terracotta',
    colors: {
      primary: '#d4a574',
      secondary: '#c9956c',
      accent: '#8b5a2b',
      background: '#faf8f5',
      text: '#3d2914',
      textSecondary: '#7a5c3e',
    },
    typography: {
      headingFont: 'Cormorant Garamond',
      bodyFont: 'Lato',
      baseSize: 16,
    },
    borderRadius: 8,
    spacing: 28,
  },
  // Elegant & Luxury Themes
  {
    id: 'noir',
    name: 'Noir',
    colors: {
      primary: '#1a1a2e',
      secondary: '#16213e',
      accent: '#e94560',
      background: '#ffffff',
      text: '#1a1a2e',
      textSecondary: '#4a4a4a',
    },
    typography: {
      headingFont: 'Playfair Display',
      bodyFont: 'Lato',
      baseSize: 16,
    },
    borderRadius: 2,
    spacing: 28,
  },
  // Studio Editorial Theme — Swiss/minimalist black & white with bold sans-serif
  {
    id: 'studio-editorial',
    name: 'Studio Editorial',
    colors: {
      primary: '#000000',
      secondary: '#333333',
      accent: '#000000',
      background: '#ffffff',
      text: '#000000',
      textSecondary: '#666666',
    },
    typography: {
      headingFont: 'Inter, Helvetica Neue, Arial, sans-serif',
      bodyFont: 'Inter, Helvetica Neue, Arial, sans-serif',
      baseSize: 17,
    },
    borderRadius: 0,
    spacing: 40,
  },

  // Creative Agency Theme - Sophisticated editorial/branding style
  {
    id: 'creative-agency',
    name: 'Creative Agency',
    colors: {
      primary: '#1a1a1a',
      secondary: '#4a4a4a',
      accent: '#f5d74f',
      background: '#f5f5f5',
      text: '#1a1a1a',
      textSecondary: '#6b6b6b',
    },
    typography: {
      headingFont: 'Cormorant Garamond',
      bodyFont: 'Inter',
      baseSize: 17,
    },
    borderRadius: 0,
    spacing: 36,
  },
  // Wellness Blog Theme - Earthy, natural, editorial style (light gray + olive green)
  {
    id: 'wellness-blog',
    name: 'Wellness Blog',
    colors: {
      primary: '#3a4a3b',
      secondary: '#5a6b5c',
      accent: '#a8b89e',
      background: '#d8dcdd',
      text: '#1a1a1a',
      textSecondary: '#4a4a4a',
    },
    typography: {
      headingFont: 'Cormorant Garamond',
      bodyFont: 'Lato',
      baseSize: 16,
    },
    borderRadius: 0,
    spacing: 32,
  },
  // Education Academy Theme - Clean, modern, child-friendly
  {
    id: 'education-academy',
    name: 'Education Academy',
    colors: {
      primary: '#000000',
      secondary: '#333333',
      accent: '#ffd700',
      background: '#ffffff',
      text: '#000000',
      textSecondary: '#666666',
    },
    typography: {
      headingFont: 'Poppins',
      bodyFont: 'Inter',
      baseSize: 16,
    },
    borderRadius: 8,
    spacing: 32,
  },
];

// Templates with pre-configured sections
export const templates: Template[] = [
  {
    id: 'designer',
    name: 'Graphic Designer',
    description: 'Perfect for showcasing visual design work with a focus on projects',
    preview: '/templates/designer.png',
    theme: themes[2], // Creative theme
    defaultSections: [
      {
        id: 'hero-1',
        type: 'hero',
        name: 'Your Name',
        title: 'Graphic Designer',
        subtitle: 'Creating Visual Stories',
        bio: 'Passionate graphic designer with 5+ years of experience in branding, digital design, and visual storytelling.',
        avatar: '',
        backgroundType: 'gradient',
        backgroundValue: 'linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%)',
        backgroundOverlayOpacity: 0,
        avatarPosition: { x: 50, y: 30 },
        namePosition: { x: 50, y: 50 },
        titlePosition: { x: 50, y: 60 },
        subtitlePosition: { x: 50, y: 68 },
        bioPosition: { x: 50, y: 78 },
        ctaButtonsPosition: { x: 50, y: 88 },
        avatarSize: 'medium',
        showName: true,
        showTitle: true,
        showSubtitle: true,
        showBio: true,
        showAvatar: true,
        showScrollIndicator: true,
        ctaButtons: [
          { id: 'cta-1a', label: 'View My Work', link: '#projects', variant: 'primary' },
          { id: 'cta-1b', label: 'Contact Me', link: '#contact', variant: 'outline' },
        ],
        layout: 'free',
      },
      {
        id: 'projects-1',
        type: 'projects',
        title: 'Featured Work',
        categories: [],
        projects: [],
        layout: 'grid',
        columnCount: 3,
        aspectRatio: '1:1',
      },
      {
        id: 'skills-1',
        type: 'skills',
        title: 'Tools & Skills',
        skills: [],
        displayStyle: 'bars',
      },
      {
        id: 'about-1',
        type: 'about',
        title: 'About Me',
        content: 'I believe great design tells a story. Every project is an opportunity to create something meaningful.',
        imageShape: 'rounded',
      },
      {
        id: 'contact-1',
        type: 'contact',
        title: "Let's Work Together",
        email: '',
        showForm: true,
      },

    ],
  },
  {
    id: 'developer',
    name: 'Developer',
    description: 'Clean and professional template for software developers',
    preview: '/templates/developer.png',
    theme: themes[3], // Minimal theme
    defaultSections: [
      {
        id: 'hero-2',
        type: 'hero',
        name: 'Your Name',
        title: 'Full Stack Developer',
        subtitle: 'Building Digital Experiences',
        bio: 'Developer passionate about creating elegant solutions to complex problems.',
        avatar: '',
        backgroundType: 'color',
        backgroundValue: '#18181b',
        backgroundOverlayOpacity: 0,
        avatarPosition: { x: 50, y: 30 },
        namePosition: { x: 50, y: 50 },
        titlePosition: { x: 50, y: 60 },
        subtitlePosition: { x: 50, y: 68 },
        bioPosition: { x: 50, y: 78 },
        ctaButtonsPosition: { x: 50, y: 88 },
        avatarSize: 'medium',
        showName: true,
        showTitle: true,
        showSubtitle: true,
        showBio: true,
        showAvatar: true,
        showScrollIndicator: true,
        ctaButtons: [
          { id: 'cta-2a', label: 'View Projects', link: '#projects', variant: 'primary' },
          { id: 'cta-2b', label: 'Contact', link: '#contact', variant: 'outline' },
        ],
        layout: 'free',
      },
      {
        id: 'skills-2',
        type: 'skills',
        title: 'Tech Stack',
        skills: [],
        displayStyle: 'bars',
      },
      {
        id: 'projects-2',
        type: 'projects',
        title: 'Projects',
        categories: [],
        projects: [],
        layout: 'grid',
        columnCount: 3,
        aspectRatio: '16:9',
      },
      {
        id: 'experience-2',
        type: 'experience',
        title: 'Experience',
        experiences: [],
        layout: 'left',
      },

      {
        id: 'contact-2',
        type: 'contact',
        title: 'Contact',
        email: '',
        showForm: true,
      },
    ],
  },
  {
    id: 'creative',
    name: 'Creative Professional',
    description: 'Versatile template for photographers, artists, and creatives',
    preview: '/templates/creative.png',
    theme: themes[1], // Dark theme
    defaultSections: [
      {
        id: 'hero-3',
        type: 'hero',
        name: 'Your Name',
        title: 'Creative Director',
        subtitle: 'Visual Artist & Storyteller',
        bio: 'Turning ideas into visual masterpieces.',
        avatar: '',
        backgroundType: 'gradient',
        backgroundValue: 'linear-gradient(135deg, #1f2937 0%, #111827 100%)',
        backgroundOverlayOpacity: 0,
        avatarPosition: { x: 50, y: 30 },
        namePosition: { x: 50, y: 50 },
        titlePosition: { x: 50, y: 60 },
        subtitlePosition: { x: 50, y: 68 },
        bioPosition: { x: 50, y: 78 },
        ctaButtonsPosition: { x: 50, y: 88 },
        avatarSize: 'medium',
        showName: true,
        showTitle: true,
        showSubtitle: true,
        showBio: true,
        showAvatar: true,
        showScrollIndicator: true,
        ctaButtons: [
          { id: 'cta-3a', label: 'View Portfolio', link: '#projects', variant: 'primary' },
          { id: 'cta-3b', label: 'Get In Touch', link: '#contact', variant: 'outline' },
        ],
        layout: 'free',
      },
      {
        id: 'projects-3',
        type: 'projects',
        title: 'Portfolio',
        categories: [],
        projects: [],
        layout: 'grid',
        columnCount: 3,

        aspectRatio: 'original',
      },
      {
        id: 'testimonials-3',
        type: 'testimonials',
        title: 'Client Love',
        testimonials: [],
        layout: 'carousel',
      },
      {
        id: 'about-3',
        type: 'about',
        title: 'My Story',
        content: 'Every creation has a story. This is mine.',
        imageShape: 'rounded',
      },

      {
        id: 'social-3',
        type: 'social',
        title: 'Follow Me',
        links: [],
      },
      {
        id: 'contact-3',
        type: 'contact',
        title: 'Get In Touch',
        email: '',
        showForm: true,
      },
    ],
  },
  // Studio Editorial Template — Swiss/minimalist black & white portfolio with bold sans-serif typography
  {
    id: 'studio-editorial',
    name: 'Studio Editorial',
    description: 'Minimalist Swiss-style portfolio with bold sans-serif typography, horizontal project grid, profile sections, and dramatic black footer with giant logo',
    preview: '/templates/studio-editorial.png',
    theme: themes.find((t) => t.id === 'studio-editorial') || defaultTheme,
    defaultSections: [
      {
        id: 'hero-se',
        type: 'hero',
        name: 'Alex Vonn',
        title: 'The Studio',
        subtitle: 'Brand Identity · Editorial Design · Digital Experiences',
        bio: 'Design is an act of translation. It is about turning complex business logic into intuitive visual languages. No fluff, just impact.',
        avatar: '',
        backgroundType: 'color',
        backgroundValue: '#ffffff',
        backgroundOverlayOpacity: 0,
        avatarPosition: { x: 50, y: 30 },
        namePosition: { x: 50, y: 12 },
        titlePosition: { x: 50, y: 35 },
        subtitlePosition: { x: 50, y: 42 },
        bioPosition: { x: 50, y: 55 },
        ctaButtonsPosition: { x: 50, y: 82 },
        avatarSize: 'medium',
        showName: true,
        showTitle: true,
        showSubtitle: true,
        showBio: true,
        showAvatar: false,
        showScrollIndicator: true,
        ctaButtons: [
          { id: 'cta-se-a', label: 'The Studio', link: '#about', variant: 'primary' },
          { id: 'cta-se-b', label: 'Selected Works', link: '#projects', variant: 'outline' },
        ],
        layout: 'free',
        textStyles: {
          name: {
            fontFamily: 'Inter, Helvetica Neue, Arial, sans-serif',
            fontWeight: '700',
            fontSize: '1.25rem',
            textTransform: 'none' as any,
            color: '#000000',
          },
          title: {
            fontFamily: 'Inter, Helvetica Neue, Arial, sans-serif',
            fontWeight: '500',
            fontSize: '1rem',
            textTransform: 'uppercase' as any,
            letterSpacing: '0.1em',
            color: '#666666',
          },
          subtitle: {
            fontFamily: 'Inter, Helvetica Neue, Arial, sans-serif',
            fontWeight: '400',
            fontSize: '0.95rem',
            color: '#999999',
            letterSpacing: '0.05em' as any,
          },
          bio: {
            fontFamily: 'Inter, Helvetica Neue, Arial, sans-serif',
            fontWeight: '800',
            fontSize: '3rem',
            lineHeight: '1.15',
            color: '#000000',
            textAlign: 'center' as any,
          },
        },
      },
      {
        id: 'projects-se',
        type: 'projects',
        title: 'Selected Works',
        categories: [
          { id: 'cat-se-1', name: 'Brand Identity' },
          { id: 'cat-se-2', name: 'Editorial Design' },
          { id: 'cat-se-3', name: 'Digital Experiences' },
        ],
        projects: [
          {
            id: 'proj-se-1',
            title: 'Meridian Coffee Co.',
            description: 'A complete brand identity system for a specialty coffee roaster — logo, packaging, and retail signage.',
            fullDescription: 'Meridian Coffee Co. needed a brand identity that reflected their commitment to single-origin coffee and their passion for the craft. We developed a complete visual system inspired by navigational meridians and the journey of coffee from bean to cup.\n\nThe identity system includes a custom logotype, packaging design for their entire range of beans, retail signage, and a comprehensive brand guidelines document.',
            imageUrl: '/templates/se-1.svg',
            images: [
              { id: 'img-se-1a', url: '/templates/se-1.svg', caption: 'Brand mark on coffee bag' },
              { id: 'img-se-1b', url: '/templates/se-1.svg', caption: 'Retail signage system' },
            ],
            category: 'Brand Identity',
            client: 'Meridian Coffee Co.',
            date: '2024',
            link: '',
            tags: ['Branding', 'Packaging', 'Logo Design'],
            featured: true,
            mediaBlocks: [
              {
                id: 'mb-se-1',
                type: 'text',
                order: 0,
                caption: '',
                textContent: {
                  text: 'The Meridian identity system draws from navigational charts and the global journey of coffee beans. Every element — from the custom logotype to the packaging grid — is built on a modular system that scales from espresso cups to retail signage.',
                  textAlign: 'left',
                  fontSize: 'medium',
                  fontWeight: 'normal',
                  fontFamily: 'Inter, Helvetica Neue, Arial, sans-serif',
                  color: '#333333',
                },
              },
              {
                id: 'mb-se-2',
                type: 'image',
                order: 1,
                caption: 'Logo system and brand mark',
                imageUrl: '/templates/se-1.svg',
                imageCaption: 'Custom logotype inspired by navigational meridians',
              },
              {
                id: 'mb-se-3',
                type: 'photoGrid',
                order: 2,
                caption: '',
                photoGridContent: {
                  items: [
                    { id: 'pg-se-1', url: '/templates/se-1.svg', caption: 'Packaging — Whole Bean' },
                    { id: 'pg-se-2', url: '/templates/se-1.svg', caption: 'Packaging — Espresso' },
                    { id: 'pg-se-3', url: '/templates/se-1.svg', caption: 'Retail Signage' },
                  ],
                  layout: 'grid',
                  columns: 3,
                  gap: 'medium',
                  showCaptions: true,
                },
              },
            ],
          },
          {
            id: 'proj-se-2',
            title: 'Aperture Magazine — Issue 07',
            description: 'Editorial design for a contemporary photography magazine, featuring a custom grid system and typographic treatment.',
            fullDescription: 'Aperture Magazine\'s seventh issue explored the theme of "Light and Shadow." We designed a custom editorial grid that allowed for both full-bleed photography and structured text layouts, creating a rhythm that guides the reader through each spread.',
            imageUrl: '/templates/se-1.svg',
            images: [
              { id: 'img-se-2a', url: '/templates/se-1.svg', caption: 'Cover spread' },
              { id: 'img-se-2b', url: '/templates/se-1.svg', caption: 'Interior spread — essay layout' },
            ],
            category: 'Editorial Design',
            client: 'Aperture Magazine',
            date: '2024',
            link: '',
            tags: ['Editorial', 'Print Design', 'Typography'],
            featured: false,
            mediaBlocks: [
              {
                id: 'mb-se-4',
                type: 'text',
                order: 0,
                caption: '',
                textContent: {
                  text: 'A custom 12-column grid system allows for both full-bleed photography and structured text layouts. The typographic pairing of bold sans-serif headlines with refined serif body text creates a visual tension that mirrors the issue\'s theme of light and shadow.',
                  textAlign: 'left',
                  fontSize: 'medium',
                  fontWeight: 'normal',
                  fontFamily: 'Inter, Helvetica Neue, Arial, sans-serif',
                  color: '#333333',
                },
              },
              {
                id: 'mb-se-5',
                type: 'image',
                order: 1,
                caption: 'Cover and spread treatment',
                imageUrl: '/templates/se-1.svg',
                imageCaption: 'Issue 07 — Light and Shadow',
              },
              {
                id: 'mb-se-5b',
                type: 'photoGrid',
                order: 2,
                caption: '',
                photoGridContent: {
                  items: [
                    { id: 'pg-se-4', url: '/templates/se-1.svg', caption: 'Spread 1 — Essay' },
                    { id: 'pg-se-5', url: '/templates/se-1.svg', caption: 'Spread 2 — Portfolio' },
                    { id: 'pg-se-6', url: '/templates/se-1.svg', caption: 'Spread 3 — Cover' },
                    { id: 'pg-se-7', url: '/templates/se-1.svg', caption: 'Spread 4 — Index' },
                  ],
                  layout: 'grid',
                  columns: 2,
                  gap: 'medium',
                  showCaptions: true,
                },
              },
            ],
          },
          {
            id: 'proj-se-3',
            title: 'Atlas Digital Platform',
            description: 'A digital experience platform for a global logistics company — UX strategy, design system, and interface design.',
            fullDescription: 'Atlas needed a unified digital platform that could serve internal teams, partners, and customers across 40+ countries. We developed a comprehensive design system, interaction patterns, and a suite of interface designs that scaled across web, tablet, and mobile.',
            imageUrl: '/templates/se-1.svg',
            images: [
              { id: 'img-se-3a', url: '/templates/se-1.svg', caption: 'Dashboard view' },
              { id: 'img-se-3b', url: '/templates/se-1.svg', caption: 'Analytics module' },
            ],
            category: 'Digital Experiences',
            client: 'Atlas Logistics',
            date: '2023',
            link: 'https://example.com',
            tags: ['UX Design', 'Design System', 'Web App'],
            featured: true,
            mediaBlocks: [
              {
                id: 'mb-se-6',
                type: 'text',
                order: 0,
                caption: '',
                textContent: {
                  text: 'The Atlas platform serves users across 40+ countries. We built a modular design system with 60+ components, each tested for accessibility (WCAG 2.1 AA) and internationalization. Data visualization patterns draw from Swiss information design principles.',
                  textAlign: 'left',
                  fontSize: 'medium',
                  fontWeight: 'normal',
                  fontFamily: 'Inter, Helvetica Neue, Arial, sans-serif',
                  color: '#333333',
                },
              },
              {
                id: 'mb-se-7',
                type: 'image',
                order: 1,
                caption: 'Design system overview',
                imageUrl: '/templates/se-1.svg',
                imageCaption: 'Component library — 60+ accessible components',
              },
              {
                id: 'mb-se-7b',
                type: 'embed',
                order: 2,
                caption: 'Live prototype',
                embedContent: {
                  embedCode: '',
                  source: 'embed',
                  url: 'https://www.figma.com/embed?embed_host=share&url=https://www.figma.com/file/example',
                  aspectRatio: '16:9',
                },
              },
            ],
          },
          {
            id: 'proj-se-4',
            title: 'Folio Art Book Series',
            description: 'A limited-edition art book series featuring emerging contemporary artists, with custom binding and typographic treatment.',
            fullDescription: 'The Folio series is a collection of limited-edition art books, each dedicated to a single emerging artist. We designed the series identity, custom binding, and individual book layouts — each tailored to the artist\'s work while maintaining series cohesion.',
            imageUrl: '/templates/se-1.svg',
            images: [
              { id: 'img-se-4a', url: '/templates/se-1.svg', caption: 'Book cover — Volume 1' },
            ],
            category: 'Editorial Design',
            client: 'Folio Press',
            date: '2023',
            link: '',
            tags: ['Book Design', 'Print', 'Art Direction'],
            featured: false,
            mediaBlocks: [
              {
                id: 'mb-se-8',
                type: 'image',
                order: 0,
                caption: '',
                imageUrl: '/templates/se-1.svg',
                imageCaption: 'Folio Volume 1 — Cover and spine detail',
              },
              {
                id: 'mb-se-9',
                type: 'text',
                order: 1,
                caption: '',
                textContent: {
                  text: 'Each volume in the Folio series uses a different paper stock and binding method, chosen to complement the artist\'s work. The series identity — a minimal foil-stamped wordmark — provides consistency without imposing on the individual book\'s design.',
                  textAlign: 'left',
                  fontSize: 'medium',
                  fontWeight: 'normal',
                  fontFamily: 'Inter, Helvetica Neue, Arial, sans-serif',
                  color: '#333333',
                },
              },
            ],
          },
          {
            id: 'proj-se-5',
            title: 'Nordic Wellness Identity',
            description: 'Brand identity for a Scandinavian wellness brand — minimal, calm, and rooted in nature.',
            fullDescription: 'Nordic Wellness needed a brand identity that captured the Scandinavian approach to wellbeing — minimal, functional, and deeply connected to nature. We created a visual system built on a muted color palette, generous whitespace, and a custom wordmark.',
            imageUrl: '/templates/se-1.svg',
            images: [],
            category: 'Brand Identity',
            client: 'Nordic Wellness',
            date: '2023',
            link: '',
            tags: ['Branding', 'Wellness', 'Minimal Design'],
            featured: false,
            mediaBlocks: [
              {
                id: 'mb-se-10',
                type: 'image',
                order: 0,
                caption: '',
                imageUrl: '/templates/se-1.svg',
                imageCaption: 'Nordic Wellness — Brand identity system',
              },
              {
                id: 'mb-se-11',
                type: 'photoGrid',
                order: 1,
                caption: '',
                photoGridContent: {
                  items: [
                    { id: 'pg-se-8', url: '/templates/se-1.svg', caption: 'Logo lockup' },
                    { id: 'pg-se-9', url: '/templates/se-1.svg', caption: 'Packaging' },
                    { id: 'pg-se-10', url: '/templates/se-1.svg', caption: 'Product line' },
                  ],
                  layout: 'grid',
                  columns: 3,
                  gap: 'medium',
                  showCaptions: true,
                },
              },
            ],
          },
          {
            id: 'proj-se-6',
            title: 'Pulse Music App',
            description: 'Mobile app design for an independent music discovery platform.',
            fullDescription: 'Pulse is a music discovery app built for independent artists and listeners who want to go beyond algorithms. We designed the entire mobile experience — from onboarding to the player interface — with a focus on tactile interactions and bold typography.',
            imageUrl: '/templates/se-1.svg',
            images: [],
            category: 'Digital Experiences',
            client: 'Pulse Music',
            date: '2024',
            link: '',
            tags: ['Mobile App', 'UI Design', 'Music'],
            featured: false,
            mediaBlocks: [
              {
                id: 'mb-se-12',
                type: 'image',
                order: 0,
                caption: '',
                imageUrl: '/templates/se-1.svg',
                imageCaption: 'Pulse Music — Player interface',
              },
            ],
          },
        ],
        layout: 'grid',
        columnCount: 3,
        aspectRatio: '1:1',
        showTitle: true,
        showCategories: true,
        textStyles: {
          title: {
            color: '#000000',
            fontFamily: 'Inter, Helvetica Neue, Arial, sans-serif',
            fontWeight: '700',
            fontSize: '2.5rem',
          },
        },
      },
      {
        id: 'about-se',
        type: 'about',
        title: 'The Studio',
        tagline: 'A design practice rooted in Swiss principles, working globally.',
        content: 'We are a multidisciplinary design studio focused on creating meaningful visual identities, editorial design, and digital experiences. Our work is rooted in Swiss design principles — clarity, precision, and purpose.',
        secondParagraph: 'We obsess over kerning tables and grid systems so you don\'t have to. Every project begins with research and ends with a system — not just a deliverable, but a framework that grows with your brand.',
        personalQuote: 'Design is not decoration. It\'s the deliberate arrangement of elements to communicate with clarity and purpose.',
        imageUrl: '',
        secondImageUrl: '',
        imageShape: 'square',
        imageLayout: 'left',
        imageSize: 'medium',
        imageBorder: false,
        imageShadow: true,
        quickFacts: [
          { id: 'qf-se-1', label: 'Years in Practice', value: '12+' },
          { id: 'qf-se-2', label: 'Brands Launched', value: '80+' },
          { id: 'qf-se-3', label: 'Countries Served', value: '15' },
          { id: 'qf-se-4', label: 'Design Awards', value: '24' },
        ],
        toolTags: ['Figma', 'Adobe CC', 'Glyphs', 'Webflow', 'Cinema 4D'],
        location: 'Zurich, Switzerland',
        availabilityStatus: 'Available for 2035',
        ctaButtonText: 'Start a Project',
        ctaButtonLink: '#contact',
        showTitle: true,
        showTagline: true,
        showBio: true,
        showPersonalQuote: true,
        showImage: false,
        showQuickFacts: true,
        showToolTags: true,
        showLocation: true,
        showCTA: true,
        showResume: false,
        showVideo: false,
        showLanguages: false,
        showGallery: false,
        showSocialLinks: false,
      },
      {
        id: 'experience-se',
        type: 'experience',
        title: 'Experience',
        experiences: [
          {
            id: 'exp-se-1',
            company: 'Alex Vonn Studio',
            position: 'Founder & Creative Director',
            startDate: '2018-01',
            endDate: '',
            description: 'Founded the studio and lead all creative direction. Built a team of 6 designers working across brand, editorial, and digital.',
            location: 'Zurich, CH',
            achievements: ['Grew studio to 6 full-time designers', 'Won 12 international design awards', 'Led 80+ brand identity projects'],
          },
          {
            id: 'exp-se-2',
            company: 'Pentagram',
            position: 'Senior Designer',
            startDate: '2014-06',
            endDate: '2017-12',
            description: 'Worked across brand identity and editorial design teams, leading projects for cultural institutions and global brands.',
            location: 'London, UK',
            achievements: ['Led rebrand for Tate Modern', 'Designed 3 award-winning annual reports'],
          },
          {
            id: 'exp-se-3',
            company: 'IDEO',
            position: 'Designer',
            startDate: '2012-01',
            endDate: '2014-05',
            description: 'Human-centered design across digital and physical touchpoints for healthcare and education clients.',
            location: 'Munich, DE',
            achievements: [],
          },
        ],
        layout: 'left',
        showTitle: true,
      },
      {
        id: 'education-se',
        type: 'education',
        title: 'Education',
        educations: [
          {
            id: 'edu-se-1',
            institution: 'ECAL (École cantonale d\'art de Lausanne)',
            degree: 'MA',
            field: 'Visual Communication',
            startDate: '2010-09',
            endDate: '2012-06',
            description: 'Specialized in typography and editorial design. Thesis: "Grid Systems in Contemporary Editorial Design."',
          },
          {
            id: 'edu-se-2',
            institution: 'Basel School of Design',
            degree: 'BFA',
            field: 'Visual Communication',
            startDate: '2006-09',
            endDate: '2010-06',
            description: 'Foundation in Swiss design principles, typography, and visual systems.',
          },
        ],
        showTitle: true,
      },
      {
        id: 'awards-se',
        type: 'awards',
        title: 'Recognition',
        awards: [
          { id: 'awd-se-1', title: 'Brand New — Best Identity', organization: 'UnderConsideration', year: '2024', description: 'Meridian Coffee Co. identity system' },
          { id: 'awd-se-2', title: 'D&AD Wood Pencil', organization: 'D&AD', year: '2023', description: 'Aperture Magazine editorial design' },
          { id: 'awd-se-3', title: 'Swiss Design Award', organization: 'Swiss Federal Office of Culture', year: '2023', description: 'Folio Art Book Series' },
          { id: 'awd-se-4', title: 'Type Directors Club — Certificate of Excellence', organization: 'TDC', year: '2022', description: 'Custom typeface for Nordic Wellness' },
          { id: 'awd-se-5', title: 'European Design Award — Silver', organization: 'ED Awards', year: '2021', description: 'Atlas Digital Platform design system' },
        ],
        showTitle: true,
      },
      {
        id: 'contact-se',
        type: 'contact',
        title: 'Start a Conversation',
        email: 'hello@alexvonn.studio',
        phone: '+41 44 123 45 67',
        location: 'Zurich, Switzerland',
        showForm: true,
        showEmail: true,
        showPhone: true,
        showLocation: true,
      },
      {
        id: 'footer-se',
        type: 'footer',
        copyrightText: '© 2025 by Alex Vonn. All rights reserved.',
        showQuickLinks: true,
        showSocialIcons: true,
        showContactInfo: true,
        showBackToTop: true,
      },
    ],
  },
  // Creative Agency Template - Personal branding designer portfolio
  {
    id: 'creative-agency',
    name: 'Creative Agency',
    description: 'Personal branding portfolio with serif typography, creative profile, project showcase, and yellow expertise highlights',
    preview: '/templates/creative-agency.png',
    theme: themes.find((t) => t.id === 'creative-agency') || defaultTheme,
    defaultSections: [
      {
        id: 'hero-ca',
        type: 'hero',
        name: 'Aline Giraud',
        title: 'Brand Designer',
        subtitle: 'Designing Brands with Purpose',
        bio: 'I help businesses make a meaningful mark. My approach blends strategy, creativity, and craftsmanship to create brands that resonate with audiences and stand the test of time.',
        avatar: '',
        backgroundType: 'color',
        backgroundValue: '#f0f0f0',
        backgroundOverlayOpacity: 0,
        // Centered editorial layout
        avatarPosition: { x: 50, y: 30 },
        namePosition: { x: 50, y: 15 },
        titlePosition: { x: 50, y: 28 },
        subtitlePosition: { x: 50, y: 42 },
        bioPosition: { x: 50, y: 60 },
        ctaButtonsPosition: { x: 50, y: 82 },
        avatarSize: 'medium',
        showName: true,
        showTitle: true,
        showSubtitle: true,
        showBio: true,
        showAvatar: false,
        showScrollIndicator: true,
        ctaButtons: [
          { id: 'cta-ca-a', label: 'View My Work', link: '#projects', variant: 'primary' },
          { id: 'cta-ca-b', label: 'Start a Project', link: '#contact', variant: 'outline' },
        ],
        layout: 'free',
        textStyles: {
          name: {
            fontFamily: 'Cormorant Garamond',
            fontWeight: '600',
            fontSize: '1.3rem',
            color: '#6b6b6b',
            textTransform: 'uppercase' as any,
            letterSpacing: '0.1em',
          },
          title: {
            fontFamily: 'Cormorant Garamond',
            fontWeight: '400',
            fontSize: '1rem',
            color: '#6b6b6b',
            textTransform: 'uppercase' as any,
            letterSpacing: '0.1em',
          },
          subtitle: {
            fontFamily: 'Cormorant Garamond',
            fontWeight: '700',
            fontSize: '3rem',
            lineHeight: '1.15',
            color: '#1a1a1a',
            textAlign: 'center' as any,
          },
          bio: {
            fontFamily: 'Cormorant Garamond',
            fontWeight: '400',
            fontSize: '1.15rem',
            lineHeight: '1.7',
            color: '#4a4a4a',
            textAlign: 'center' as any,
          },
        },
      },
      {
        id: 'about-ca',
        type: 'about',
        title: 'Creative Profile',
        content: 'Role: Brand Designer & Visual Identity Specialist\n\nFocus: Brand Identity Design, Art Direction, Visual Systems, Concept Development, Strategic Brand Support\n\nWorks With: Ambitious founders & businesses',
        imageShape: 'square',
      },
      {
        id: 'skills-ca',
        type: 'skills',
        title: 'My Expertise',
        skills: [
          { id: 'skill-ca-1', name: 'Brand Strategy', level: 90, icon: 'star', category: 'Strategy' },
          { id: 'skill-ca-2', name: 'Visual Identity Design', level: 95, icon: 'palette', category: 'Design' },
        ],
        displayStyle: 'tags',
      },
      {
        id: 'projects-ca',
        type: 'projects',
        title: 'Selected Work',
        categories: [],
        projects: [],
        layout: 'grid',
        columnCount: 2,
        aspectRatio: '4:3',
      },
      {
        id: 'testimonials-ca',
        type: 'testimonials',
        title: 'What My Clients Say',
        testimonials: [],
        layout: 'grid',
      },
      {
        id: 'cta-ca',
        type: 'ctaBanner',
        title: 'Branding That Resonates. Let\'s Build It Together.',
        subtitle: 'Ready to create something meaningful?',
        buttonText: 'Start a Project',
        buttonLink: '#contact',
        backgroundType: 'color',
        backgroundValue: '#1a1a1a',
      },
      {
        id: 'contact-ca',
        type: 'contact',
        title: 'Get In Touch',
        email: '',
        showForm: true,
      },
      {
        id: 'footer-ca',
        type: 'footer',
        copyrightText: '© 2025 by Aline Giraud. All rights reserved.',
        showQuickLinks: true,
        showSocialIcons: true,
        showContactInfo: true,
        showBackToTop: true,
      },
    ],
  },
  // Wellness Blog Template - Wellness coach/nutritionist with light gray + olive green sections
  {
    id: 'wellness-blog',
    name: 'Wellness Blog',
    description: 'Wellness coach portfolio with light gray sections, olive green recipe grid, coaching services, and seasonal content',
    preview: '/templates/wellness-blog.png',
    theme: themes.find((t) => t.id === 'wellness-blog') || defaultTheme,
    defaultSections: [
      {
        id: 'hero-wb',
        type: 'hero',
        name: 'Wellness by Myhra',
        title: 'Begin Your Wellness Journey',
        subtitle: 'Natural wellness, recipes & coaching',
        bio: 'Hi, I\'m Myhra Jones. I help you transform your life through natural wellness, nourishing recipes, and personalized coaching.',
        avatar: '',
        backgroundType: 'color',
        backgroundValue: '#d8dcdd',
        backgroundOverlayOpacity: 0,
        avatarPosition: { x: 50, y: 30 },
        namePosition: { x: 50, y: 15 },
        titlePosition: { x: 50, y: 30 },
        subtitlePosition: { x: 50, y: 45 },
        bioPosition: { x: 50, y: 60 },
        ctaButtonsPosition: { x: 50, y: 80 },
        avatarSize: 'medium',
        showName: true,
        showTitle: true,
        showSubtitle: true,
        showBio: true,
        showAvatar: false,
        showScrollIndicator: true,
        ctaButtons: [
          { id: 'cta-wb-a', label: 'Book a Free Consultation', link: '#contact', variant: 'primary' },
          { id: 'cta-wb-b', label: 'Work With Me', link: '#services', variant: 'outline' },
        ],
        layout: 'free',
        textStyles: {
          name: {
            fontFamily: 'Cormorant Garamond',
            fontWeight: '700',
            fontSize: '1.5rem',
            textTransform: 'uppercase' as any,
            letterSpacing: '0.15em',
            color: '#3a4a3b',
          },
          title: {
            fontFamily: 'Cormorant Garamond',
            fontWeight: '700',
            fontSize: '3rem',
            lineHeight: '1.15',
            color: '#1a1a1a',
            textAlign: 'center' as any,
          },
          subtitle: {
            fontFamily: 'Lato',
            fontWeight: '400',
            fontSize: '1.1rem',
            color: '#4a4a4a',
            textAlign: 'center' as any,
          },
          bio: {
            fontFamily: 'Lato',
            fontWeight: '400',
            fontSize: '1rem',
            lineHeight: '1.7',
            color: '#4a4a4a',
            textAlign: 'center' as any,
          },
        },
      },
      {
        id: 'about-wb',
        type: 'about',
        title: 'Hi, I\'m Myhra Jones',
        content: 'I\'m a wellness coach and nutritionist passionate about helping you live your best life through natural wellness. My approach combines traditional wisdom with modern nutrition science to create sustainable, healthy habits.',
        imageShape: 'square',
      },
      {
        id: 'services-wb',
        type: 'services',
        title: 'Services',
        services: [
          { id: 'svc-wb-1', icon: 'star', title: '1:1 Coaching', description: 'The Transformation Program — personalized coaching to transform your wellness journey. $700.' },
          { id: 'svc-wb-2', icon: 'book', title: 'Online Lessons', description: 'Self-paced wellness courses covering nutrition, mindfulness, and natural skincare.' },
          { id: 'svc-wb-3', icon: 'heart', title: 'Consultation', description: 'Book a free consultation to discuss your wellness goals and create a personalized plan.' },
        ],
      },
      {
        id: 'blog-wb',
        type: 'blog',
        title: 'Recipes',
        posts: [],
        layout: 'grid',
      },
      {
        id: 'newsletter-wb',
        type: 'newsletter',
        title: 'Join Our Community',
        subtitle: 'Get weekly recipes and wellness tips delivered to your inbox.',
        placeholder: 'Enter your email',
        buttonText: 'Subscribe',
        backgroundType: 'color',
        backgroundValue: '#3a4a3b',
      },
      {
        id: 'contact-wb',
        type: 'contact',
        title: 'Get In Touch',
        email: '',
        showForm: true,
      },
      {
        id: 'footer-wb',
        type: 'footer',
        copyrightText: '© 2025 by Wellness by Myhra. All rights reserved.',
        showQuickLinks: true,
        showSocialIcons: true,
        showContactInfo: true,
        showBackToTop: true,
      },
    ],
  },
  // Education Academy Template - Clean, modern, child-friendly
  {
    id: 'education-academy',
    name: 'Education Academy',
    description: 'Modern education site with black header, yellow accent CTAs, program grids, and blog section',
    preview: '/templates/education-academy.png',
    theme: themes.find((t) => t.id === 'education-academy') || defaultTheme,
    defaultSections: [
      {
        id: 'hero-ea',
        type: 'hero',
        name: 'Little Comets Academy',
        title: 'Keep Their Growing Minds Engaged',
        subtitle: 'Where Curiosity Meets Discovery',
        bio: 'A nurturing learning environment where children explore, create, and grow. Our programs are designed to spark curiosity and build confidence.',
        avatar: '',
        backgroundType: 'color',
        backgroundValue: '#ffffff',
        backgroundOverlayOpacity: 0,
        // Centered layout with image
        avatarPosition: { x: 50, y: 30 },
        namePosition: { x: 50, y: 15 },
        titlePosition: { x: 50, y: 35 },
        subtitlePosition: { x: 50, y: 50 },
        bioPosition: { x: 50, y: 65 },
        ctaButtonsPosition: { x: 50, y: 82 },
        avatarSize: 'medium',
        showName: true,
        showTitle: true,
        showSubtitle: true,
        showBio: true,
        showAvatar: false,
        showScrollIndicator: true,
        ctaButtons: [
          { id: 'cta-ea-a', label: 'Get Started', link: '#contact', variant: 'primary' },
        ],
        layout: 'free',
        textStyles: {
          name: {
            fontFamily: 'Poppins',
            fontWeight: '700',
            fontSize: '1.5rem',
            color: '#000000',
          },
          title: {
            fontFamily: 'Poppins',
            fontWeight: '700',
            fontSize: '2.5rem',
            lineHeight: '1.2',
            color: '#000000',
            textAlign: 'center' as any,
          },
          subtitle: {
            fontFamily: 'Inter',
            fontWeight: '500',
            fontSize: '1.1rem',
            color: '#666666',
            textAlign: 'center' as any,
          },
          bio: {
            fontFamily: 'Inter',
            fontWeight: '400',
            fontSize: '1rem',
            lineHeight: '1.7',
            color: '#666666',
            textAlign: 'center' as any,
          },
        },
      },
      {
        id: 'services-ea',
        type: 'services',
        title: 'Our Programs',
        services: [
          { id: 'svc-1', icon: 'star', title: 'Little Kids Club', description: 'Ages 2-6. A playful introduction to learning through exploration and creativity.' },
          { id: 'svc-2', icon: 'rocket', title: 'Big Kids', description: 'Ages 7-10. Engaging activities that build critical thinking and social skills.' },
          { id: 'svc-3', icon: 'book', title: 'After School', description: 'Ages 5-12. Homework help, enrichment activities, and creative projects.' },
        ],
      },
      {
        id: 'about-ea',
        type: 'about',
        title: 'About Us',
        content: 'At Little Comets Academy, we believe every child is a star waiting to shine. Our experienced educators create a safe, joyful environment where curiosity flourishes and every child feels valued.',
        imageShape: 'rounded',
      },
      {
        id: 'blog-ea',
        type: 'blog',
        title: 'Inspiration Station',
        posts: [],
        layout: 'grid',
      },
      {
        id: 'cta-ea',
        type: 'ctaBanner',
        title: 'Join the Club',
        subtitle: 'Special Offer: Free Introductory Course',
        buttonText: 'Get Started for Free',
        buttonLink: '#contact',
        backgroundType: 'color',
        backgroundValue: '#ffd700',
      },
      {
        id: 'contact-ea',
        type: 'contact',
        title: 'Get In Touch',
        email: '',
        showForm: true,
      },
      {
        id: 'footer-ea',
        type: 'footer',
        copyrightText: '© 2025 by Little Comets Academy. All rights reserved.',
        showQuickLinks: true,
        showSocialIcons: true,
        showContactInfo: true,
        showBackToTop: true,
      },
    ],
  },
];

// Section type configurations
export const sectionConfig = {
  hero: {
    name: 'Hero / Introduction',
    icon: 'User',
    description: 'Main introduction section with name, title, and bio',
  },
  about: {
    name: 'About',
    icon: 'FileText',
    description: 'Tell your story and background',
  },
  projects: {
    name: 'Projects',
    icon: 'Briefcase',
    description: 'Showcase your work and projects',
  },
  skills: {
    name: 'Skills',
    icon: 'Star',
    description: 'Display your skills and expertise',
  },
  experience: {
    name: 'Experience',
    icon: 'Building',
    description: 'Work history and professional experience',
  },
  education: {
    name: 'Education',
    icon: 'GraduationCap',
    description: 'Educational background and certifications',
  },
  testimonials: {
    name: 'Testimonials',
    icon: 'MessageSquare',
    description: 'Client and colleague recommendations',
  },
  contact: {
    name: 'Contact',
    icon: 'Mail',
    description: 'Contact information and form',
  },
  social: {
    name: 'Social Links',
    icon: 'Share2',
    description: 'Links to social media profiles',
  },
  footer: {
    name: 'Footer',
    icon: 'PanelBottom',
    description: 'Footer with copyright, links, and social icons',
  },
  ctaBanner: {
    name: 'CTA Banner',
    icon: 'Megaphone',
    description: 'Call-to-action banner before footer',
  },
  services: {
    name: 'Services',
    icon: 'Layers',
    description: 'What I do — services you offer',
  },
  process: {
    name: 'Process',
    icon: 'Workflow',
    description: 'How I work — your design process steps',
  },
  stats: {
    name: 'Stats',
    icon: 'BarChart3',
    description: 'Quick facts and numbers about your work',
  },
  awards: {
    name: 'Awards',
    icon: 'Trophy',
    description: 'Awards and recognition you have received',
  },
  press: {
    name: 'Press',
    icon: 'Newspaper',
    description: 'Featured in — press logos and mentions',
  },
  certifications: {
    name: 'Certifications',
    icon: 'BadgeCheck',
    description: 'Professional certifications and courses',
  },
  blog: {
    name: 'Blog',
    icon: 'Newspaper',
    description: 'Articles and blog posts',
  },
  faq: {
    name: 'FAQ',
    icon: 'HelpCircle',
    description: 'Frequently asked questions',
  },
  newsletter: {
    name: 'Newsletter',
    icon: 'Mail',
    description: 'Email newsletter signup form',
  },

};




// Google Fonts that can be used
export const availableFonts = [
  'Inter',
  'Playfair Display',
  'Lato',
  'Merriweather',
  'Open Sans',
  'Lora',
  'Poppins',
  'Roboto',
  'Montserrat',
  'Raleway',
  'Space Grotesk',
  'Cormorant Garamond',
  'Georgia',
];
